# Generated by Django 3.0.7 on 2020-06-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='school_ID',
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
