# Generated by Django 3.0.7 on 2020-06-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_manager', '0002_auto_20200608_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_school',
            old_name='school_ID',
            new_name='school_name',
        ),
    ]
